/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/Demo.vue')['default']
    Diagram: typeof import('./src/components/Diagram.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    ModuleList: typeof import('./src/components/ModuleList.vue')['default']
    Output: typeof import('./src/components/Output.vue')['default']
  }
}
